### ISSUE TITLE
I would appreciate a little understanding on a few things

### ISSUE THREAD

**Issue by JacksiroKe** [eneshecan/Gtk-Web-Browser#1]
Kindly help me understand why `cmake --build build/debug` fails with an error: `Error: could not load cache` but when I run `cmake --build ./` it actually builds successfully.

But I have to move the binary to build/debug for it to run. I am still a student in these stuff.

**Comment by xeco23** [comment]
Hi, sure. I think the command is there wrong. I will fix it asap. You need to go into the build/debug directory and run `cmake ../..` there. After that, don't forget to invoke `make` to build.

**Comment by xeco23** [comment]
Since we get the fixed ui paths in the code, they need to correspond to their exact places. I know this is not a good solution, maybe treating them as if they are in the build directory and suggest users copy UI files there is better. I will make it possible and document it in the readme soon.

**Comment by JacksiroKe** [comment]
thanks I appreciate your response. I am learning a lot already and I have own workrounds based on what i found elsewhere
